// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.3
// source: comunicacao.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BIQueryService_GetMarcaStats_FullMethodName       = "/comunicacao.BIQueryService/GetMarcaStats"
	BIQueryService_GetContagemSegmento_FullMethodName = "/comunicacao.BIQueryService/GetContagemSegmento"
	BIQueryService_GetLocalizacaoStats_FullMethodName = "/comunicacao.BIQueryService/GetLocalizacaoStats"
)

// BIQueryServiceClient is the client API for BIQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BIQueryServiceClient interface {
	GetMarcaStats(ctx context.Context, in *Filtro, opts ...grpc.CallOption) (*MarcaStats, error)
	GetContagemSegmento(ctx context.Context, in *Filtro, opts ...grpc.CallOption) (*Resultado, error)
	GetLocalizacaoStats(ctx context.Context, in *Filtro, opts ...grpc.CallOption) (*LocalizacaoStats, error)
}

type bIQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBIQueryServiceClient(cc grpc.ClientConnInterface) BIQueryServiceClient {
	return &bIQueryServiceClient{cc}
}

func (c *bIQueryServiceClient) GetMarcaStats(ctx context.Context, in *Filtro, opts ...grpc.CallOption) (*MarcaStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarcaStats)
	err := c.cc.Invoke(ctx, BIQueryService_GetMarcaStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bIQueryServiceClient) GetContagemSegmento(ctx context.Context, in *Filtro, opts ...grpc.CallOption) (*Resultado, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resultado)
	err := c.cc.Invoke(ctx, BIQueryService_GetContagemSegmento_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bIQueryServiceClient) GetLocalizacaoStats(ctx context.Context, in *Filtro, opts ...grpc.CallOption) (*LocalizacaoStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocalizacaoStats)
	err := c.cc.Invoke(ctx, BIQueryService_GetLocalizacaoStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BIQueryServiceServer is the server API for BIQueryService service.
// All implementations must embed UnimplementedBIQueryServiceServer
// for forward compatibility.
type BIQueryServiceServer interface {
	GetMarcaStats(context.Context, *Filtro) (*MarcaStats, error)
	GetContagemSegmento(context.Context, *Filtro) (*Resultado, error)
	GetLocalizacaoStats(context.Context, *Filtro) (*LocalizacaoStats, error)
	mustEmbedUnimplementedBIQueryServiceServer()
}

// UnimplementedBIQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBIQueryServiceServer struct{}

func (UnimplementedBIQueryServiceServer) GetMarcaStats(context.Context, *Filtro) (*MarcaStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarcaStats not implemented")
}
func (UnimplementedBIQueryServiceServer) GetContagemSegmento(context.Context, *Filtro) (*Resultado, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContagemSegmento not implemented")
}
func (UnimplementedBIQueryServiceServer) GetLocalizacaoStats(context.Context, *Filtro) (*LocalizacaoStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLocalizacaoStats not implemented")
}
func (UnimplementedBIQueryServiceServer) mustEmbedUnimplementedBIQueryServiceServer() {}
func (UnimplementedBIQueryServiceServer) testEmbeddedByValue()                        {}

// UnsafeBIQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BIQueryServiceServer will
// result in compilation errors.
type UnsafeBIQueryServiceServer interface {
	mustEmbedUnimplementedBIQueryServiceServer()
}

func RegisterBIQueryServiceServer(s grpc.ServiceRegistrar, srv BIQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedBIQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BIQueryService_ServiceDesc, srv)
}

func _BIQueryService_GetMarcaStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filtro)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BIQueryServiceServer).GetMarcaStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BIQueryService_GetMarcaStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BIQueryServiceServer).GetMarcaStats(ctx, req.(*Filtro))
	}
	return interceptor(ctx, in, info, handler)
}

func _BIQueryService_GetContagemSegmento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filtro)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BIQueryServiceServer).GetContagemSegmento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BIQueryService_GetContagemSegmento_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BIQueryServiceServer).GetContagemSegmento(ctx, req.(*Filtro))
	}
	return interceptor(ctx, in, info, handler)
}

func _BIQueryService_GetLocalizacaoStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filtro)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BIQueryServiceServer).GetLocalizacaoStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BIQueryService_GetLocalizacaoStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BIQueryServiceServer).GetLocalizacaoStats(ctx, req.(*Filtro))
	}
	return interceptor(ctx, in, info, handler)
}

// BIQueryService_ServiceDesc is the grpc.ServiceDesc for BIQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BIQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comunicacao.BIQueryService",
	HandlerType: (*BIQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarcaStats",
			Handler:    _BIQueryService_GetMarcaStats_Handler,
		},
		{
			MethodName: "GetContagemSegmento",
			Handler:    _BIQueryService_GetContagemSegmento_Handler,
		},
		{
			MethodName: "GetLocalizacaoStats",
			Handler:    _BIQueryService_GetLocalizacaoStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comunicacao.proto",
}
