// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: comunicacao.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filtro struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Termo         string                 `protobuf:"bytes,1,opt,name=termo,proto3" json:"termo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filtro) Reset() {
	*x = Filtro{}
	mi := &file_comunicacao_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filtro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filtro) ProtoMessage() {}

func (x *Filtro) ProtoReflect() protoreflect.Message {
	mi := &file_comunicacao_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filtro.ProtoReflect.Descriptor instead.
func (*Filtro) Descriptor() ([]byte, []int) {
	return file_comunicacao_proto_rawDescGZIP(), []int{0}
}

func (x *Filtro) GetTermo() string {
	if x != nil {
		return x.Termo
	}
	return ""
}

type Resultado struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valor         float32                `protobuf:"fixed32,1,opt,name=valor,proto3" json:"valor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resultado) Reset() {
	*x = Resultado{}
	mi := &file_comunicacao_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resultado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resultado) ProtoMessage() {}

func (x *Resultado) ProtoReflect() protoreflect.Message {
	mi := &file_comunicacao_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resultado.ProtoReflect.Descriptor instead.
func (*Resultado) Descriptor() ([]byte, []int) {
	return file_comunicacao_proto_rawDescGZIP(), []int{1}
}

func (x *Resultado) GetValor() float32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

type MarcaStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	MediaPreco    float32                `protobuf:"fixed32,2,opt,name=media_preco,json=mediaPreco,proto3" json:"media_preco,omitempty"`
	MediaKms      float32                `protobuf:"fixed32,3,opt,name=media_kms,json=mediaKms,proto3" json:"media_kms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarcaStats) Reset() {
	*x = MarcaStats{}
	mi := &file_comunicacao_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarcaStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarcaStats) ProtoMessage() {}

func (x *MarcaStats) ProtoReflect() protoreflect.Message {
	mi := &file_comunicacao_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarcaStats.ProtoReflect.Descriptor instead.
func (*MarcaStats) Descriptor() ([]byte, []int) {
	return file_comunicacao_proto_rawDescGZIP(), []int{2}
}

func (x *MarcaStats) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MarcaStats) GetMediaPreco() float32 {
	if x != nil {
		return x.MediaPreco
	}
	return 0
}

func (x *MarcaStats) GetMediaKms() float32 {
	if x != nil {
		return x.MediaKms
	}
	return 0
}

type LocalizacaoStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCarros   int32                  `protobuf:"varint,1,opt,name=total_carros,json=totalCarros,proto3" json:"total_carros,omitempty"`
	ValorTotal    float32                `protobuf:"fixed32,2,opt,name=valor_total,json=valorTotal,proto3" json:"valor_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalizacaoStats) Reset() {
	*x = LocalizacaoStats{}
	mi := &file_comunicacao_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalizacaoStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalizacaoStats) ProtoMessage() {}

func (x *LocalizacaoStats) ProtoReflect() protoreflect.Message {
	mi := &file_comunicacao_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalizacaoStats.ProtoReflect.Descriptor instead.
func (*LocalizacaoStats) Descriptor() ([]byte, []int) {
	return file_comunicacao_proto_rawDescGZIP(), []int{3}
}

func (x *LocalizacaoStats) GetTotalCarros() int32 {
	if x != nil {
		return x.TotalCarros
	}
	return 0
}

func (x *LocalizacaoStats) GetValorTotal() float32 {
	if x != nil {
		return x.ValorTotal
	}
	return 0
}

var File_comunicacao_proto protoreflect.FileDescriptor

const file_comunicacao_proto_rawDesc = "" +
	"\n" +
	"\x11comunicacao.proto\x12\vcomunicacao\"\x1e\n" +
	"\x06Filtro\x12\x14\n" +
	"\x05termo\x18\x01 \x01(\tR\x05termo\"!\n" +
	"\tResultado\x12\x14\n" +
	"\x05valor\x18\x01 \x01(\x02R\x05valor\"`\n" +
	"\n" +
	"MarcaStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1f\n" +
	"\vmedia_preco\x18\x02 \x01(\x02R\n" +
	"mediaPreco\x12\x1b\n" +
	"\tmedia_kms\x18\x03 \x01(\x02R\bmediaKms\"V\n" +
	"\x10LocalizacaoStats\x12!\n" +
	"\ftotal_carros\x18\x01 \x01(\x05R\vtotalCarros\x12\x1f\n" +
	"\vvalor_total\x18\x02 \x01(\x02R\n" +
	"valorTotal2\xde\x01\n" +
	"\x0eBIQueryService\x12=\n" +
	"\rGetMarcaStats\x12\x13.comunicacao.Filtro\x1a\x17.comunicacao.MarcaStats\x12B\n" +
	"\x13GetContagemSegmento\x12\x13.comunicacao.Filtro\x1a\x16.comunicacao.Resultado\x12I\n" +
	"\x13GetLocalizacaoStats\x12\x13.comunicacao.Filtro\x1a\x1d.comunicacao.LocalizacaoStatsB\x06Z\x04./pbb\x06proto3"

var (
	file_comunicacao_proto_rawDescOnce sync.Once
	file_comunicacao_proto_rawDescData []byte
)

func file_comunicacao_proto_rawDescGZIP() []byte {
	file_comunicacao_proto_rawDescOnce.Do(func() {
		file_comunicacao_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comunicacao_proto_rawDesc), len(file_comunicacao_proto_rawDesc)))
	})
	return file_comunicacao_proto_rawDescData
}

var file_comunicacao_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_comunicacao_proto_goTypes = []any{
	(*Filtro)(nil),           // 0: comunicacao.Filtro
	(*Resultado)(nil),        // 1: comunicacao.Resultado
	(*MarcaStats)(nil),       // 2: comunicacao.MarcaStats
	(*LocalizacaoStats)(nil), // 3: comunicacao.LocalizacaoStats
}
var file_comunicacao_proto_depIdxs = []int32{
	0, // 0: comunicacao.BIQueryService.GetMarcaStats:input_type -> comunicacao.Filtro
	0, // 1: comunicacao.BIQueryService.GetContagemSegmento:input_type -> comunicacao.Filtro
	0, // 2: comunicacao.BIQueryService.GetLocalizacaoStats:input_type -> comunicacao.Filtro
	2, // 3: comunicacao.BIQueryService.GetMarcaStats:output_type -> comunicacao.MarcaStats
	1, // 4: comunicacao.BIQueryService.GetContagemSegmento:output_type -> comunicacao.Resultado
	3, // 5: comunicacao.BIQueryService.GetLocalizacaoStats:output_type -> comunicacao.LocalizacaoStats
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_comunicacao_proto_init() }
func file_comunicacao_proto_init() {
	if File_comunicacao_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comunicacao_proto_rawDesc), len(file_comunicacao_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comunicacao_proto_goTypes,
		DependencyIndexes: file_comunicacao_proto_depIdxs,
		MessageInfos:      file_comunicacao_proto_msgTypes,
	}.Build()
	File_comunicacao_proto = out.File
	file_comunicacao_proto_goTypes = nil
	file_comunicacao_proto_depIdxs = nil
}
