# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import comunicacao_pb2 as comunicacao__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in comunicacao_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BIQueryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMarcaStats = channel.unary_unary(
                '/comunicacao.BIQueryService/GetMarcaStats',
                request_serializer=comunicacao__pb2.Filtro.SerializeToString,
                response_deserializer=comunicacao__pb2.MarcaStats.FromString,
                _registered_method=True)
        self.GetContagemSegmento = channel.unary_unary(
                '/comunicacao.BIQueryService/GetContagemSegmento',
                request_serializer=comunicacao__pb2.Filtro.SerializeToString,
                response_deserializer=comunicacao__pb2.Resultado.FromString,
                _registered_method=True)
        self.GetLocalizacaoStats = channel.unary_unary(
                '/comunicacao.BIQueryService/GetLocalizacaoStats',
                request_serializer=comunicacao__pb2.Filtro.SerializeToString,
                response_deserializer=comunicacao__pb2.LocalizacaoStats.FromString,
                _registered_method=True)


class BIQueryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMarcaStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContagemSegmento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocalizacaoStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BIQueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMarcaStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarcaStats,
                    request_deserializer=comunicacao__pb2.Filtro.FromString,
                    response_serializer=comunicacao__pb2.MarcaStats.SerializeToString,
            ),
            'GetContagemSegmento': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContagemSegmento,
                    request_deserializer=comunicacao__pb2.Filtro.FromString,
                    response_serializer=comunicacao__pb2.Resultado.SerializeToString,
            ),
            'GetLocalizacaoStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocalizacaoStats,
                    request_deserializer=comunicacao__pb2.Filtro.FromString,
                    response_serializer=comunicacao__pb2.LocalizacaoStats.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'comunicacao.BIQueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('comunicacao.BIQueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BIQueryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMarcaStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/comunicacao.BIQueryService/GetMarcaStats',
            comunicacao__pb2.Filtro.SerializeToString,
            comunicacao__pb2.MarcaStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContagemSegmento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/comunicacao.BIQueryService/GetContagemSegmento',
            comunicacao__pb2.Filtro.SerializeToString,
            comunicacao__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLocalizacaoStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/comunicacao.BIQueryService/GetLocalizacaoStats',
            comunicacao__pb2.Filtro.SerializeToString,
            comunicacao__pb2.LocalizacaoStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
