# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: comunicacao.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'comunicacao.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63omunicacao.proto\x12\x0b\x63omunicacao\"\x17\n\x06\x46iltro\x12\r\n\x05termo\x18\x01 \x01(\t\"\x1a\n\tResultado\x12\r\n\x05valor\x18\x01 \x01(\x02\"C\n\nMarcaStats\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x13\n\x0bmedia_preco\x18\x02 \x01(\x02\x12\x11\n\tmedia_kms\x18\x03 \x01(\x02\"=\n\x10LocalizacaoStats\x12\x14\n\x0ctotal_carros\x18\x01 \x01(\x05\x12\x13\n\x0bvalor_total\x18\x02 \x01(\x02\x32\xde\x01\n\x0e\x42IQueryService\x12=\n\rGetMarcaStats\x12\x13.comunicacao.Filtro\x1a\x17.comunicacao.MarcaStats\x12\x42\n\x13GetContagemSegmento\x12\x13.comunicacao.Filtro\x1a\x16.comunicacao.Resultado\x12I\n\x13GetLocalizacaoStats\x12\x13.comunicacao.Filtro\x1a\x1d.comunicacao.LocalizacaoStatsB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comunicacao_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_FILTRO']._serialized_start=34
  _globals['_FILTRO']._serialized_end=57
  _globals['_RESULTADO']._serialized_start=59
  _globals['_RESULTADO']._serialized_end=85
  _globals['_MARCASTATS']._serialized_start=87
  _globals['_MARCASTATS']._serialized_end=154
  _globals['_LOCALIZACAOSTATS']._serialized_start=156
  _globals['_LOCALIZACAOSTATS']._serialized_end=217
  _globals['_BIQUERYSERVICE']._serialized_start=220
  _globals['_BIQUERYSERVICE']._serialized_end=442
# @@protoc_insertion_point(module_scope)
